/*
 * This file is generated by scripts/generate-types.js
 * Do not edit this file directly.
 */

declare module 'uzumaki' {
  //#region js/types.d.ts
  type NodeId = number;
  interface WindowPosition {
    x: number;
    y: number;
  }
  interface WindowSize {
    width: number;
    height: number;
  }
  type WindowTheme = 'light' | 'dark' | 'system';
  type WindowLevel = 'normal' | 'alwaysOnTop' | 'alwaysOnBottom';
  interface WindowOptions {
    width?: number;
    height?: number;
    title?: string;
    visible?: boolean;
    resizable?: boolean;
    decorations?: boolean;
    transparent?: boolean;
    maximized?: boolean;
    minimized?: boolean;
    fullscreen?: boolean;
    windowLevel?: WindowLevel;
    minWidth?: number;
    minHeight?: number;
    maxWidth?: number;
    maxHeight?: number;
    position?: WindowPosition;
    theme?: WindowTheme;
    active?: boolean;
    contentProtected?: boolean;
    closable?: boolean;
    minimizable?: boolean;
    maximizable?: boolean;
    rootStyles?: Record<string, unknown>;
  }
  //#endregion
  //#region js/core.d.ts
  interface CoreNode {
    readonly id: NodeId;
    readonly windowId: number;
    readonly nodeType: number;
    readonly nodeName: string;
    readonly parentNodeId: NodeId | null;
    readonly firstChildId: NodeId | null;
    readonly lastChildId: NodeId | null;
    readonly nextSiblingId: NodeId | null;
    readonly previousSiblingId: NodeId | null;
    textContent: string | null;
    appendChild(child: CoreNode): void;
    insertBefore(child: CoreNode, before: CoreNode | null): void;
    removeChild(child: CoreNode): void;
    remove(): void;
    setStrAttribute(name: string, value: string): void;
    setNumberAttribute(name: string, value: number): void;
    setBoolAttribute(name: string, value: boolean): void;
    removeAttribute(name: string): void;
    getAttribute(name: string): unknown;
  }
  //#endregion
  //#region js/event-target.d.ts
  interface ListenerOptions {
    capture?: boolean;
  }
  interface EmitterEntry<F extends Function = Function> {
    handler: F;
    capture: boolean;
  }
  interface EventTargetOptions<M extends Record<string, any>> {
    dispatch?: <K extends keyof M>(name: K, event: M[K]) => boolean | undefined;
  }
  declare class UzEventTarget<M extends Record<string, any>> {
    private _entries;
    private _dispatch?;
    constructor(options?: EventTargetOptions<M>);
    on<K extends keyof M>(
      name: K,
      handler: (event: M[K]) => void,
      options?: ListenerOptions,
    ): void;
    off<K extends keyof M>(
      name: K,
      handler: (event: M[K]) => void,
      options?: ListenerOptions,
    ): void;
    emit<K extends keyof M>(name: K, event: M[K]): boolean;
    /** @internal Fire local listeners without DOM-style propagation. */
    _emitLocal<K extends keyof M>(name: K, event: M[K]): boolean;
    /** @internal Used by the dispatcher to filter handlers by phase. */
    _listeners<K extends keyof M>(name: K): readonly EmitterEntry[] | undefined;
    /** @internal */
    _hasAny(): boolean;
    _listenerCount<K extends keyof M>(name: K): number;
    /** @internal */
    _clear(): void;
  }
  //#endregion
  //#region js/events.d.ts
  declare const enum EventType {
    MouseMove = 0,
    MouseDown = 1,
    MouseUp = 2,
    Click = 3,
    KeyDown = 10,
    KeyUp = 11,
    Input = 20,
    Focus = 21,
    Blur = 22,
    Copy = 25,
    Cut = 26,
    Paste = 27,
  }
  declare const enum EventPhase {
    None = 0,
    Capture = 1,
    Target = 2,
    Bubble = 3,
  }
  interface UzumakiEvent<T extends UzNode = UzNode> {
    readonly type: EventType | string;
    readonly target: UzNode | null;
    currentTarget: T | null;
    readonly eventPhase: EventPhase;
    readonly bubbles: boolean;
    readonly defaultPrevented: boolean;
    stopPropagation(): void;
    stopImmediatePropagation(): void;
    preventDefault(): void;
  }
  interface UzMouseEvent<T extends UzNode = UzNode> extends UzumakiEvent<T> {
    readonly x: number;
    readonly y: number;
    readonly screenX: number;
    readonly screenY: number;
    readonly button: number;
    readonly buttons: number;
  }
  interface UzKeyboardEvent<T extends UzNode = UzNode> extends UzumakiEvent<T> {
    readonly key: string;
    readonly code: string;
    readonly keyCode: number;
    readonly repeat: boolean;
    readonly ctrlKey: boolean;
    readonly altKey: boolean;
    readonly shiftKey: boolean;
    readonly metaKey: boolean;
  }
  interface UzInputEvent<T extends UzNode = UzNode> extends UzumakiEvent<T> {
    readonly inputType: string;
    readonly data: string | null;
  }
  interface UzFocusEvent<T extends UzNode = UzNode> extends UzumakiEvent<T> {}
  interface UzClipboardEvent<
    T extends UzNode = UzNode,
  > extends UzumakiEvent<T> {
    readonly selectionText: string | null;
    readonly clipboardText: string | null;
  }
  interface UzumakiResizeEvent<
    T extends UzNode = UzNode,
  > extends UzumakiEvent<T> {
    readonly width: number;
    readonly height: number;
  }
  /** DOM-style events that can be attached to any element. */
  interface UzEventMap {
    mousemove: UzMouseEvent;
    mousedown: UzMouseEvent;
    mouseup: UzMouseEvent;
    click: UzMouseEvent;
    keydown: UzKeyboardEvent;
    keyup: UzKeyboardEvent;
    input: UzInputEvent;
    change: UzInputEvent;
    focus: UzFocusEvent;
    blur: UzFocusEvent;
    copy: UzClipboardEvent;
    cut: UzClipboardEvent;
    paste: UzClipboardEvent;
  }
  /** Window receives all DOM events (for bubble/capture) plus its lifecycle events. */
  interface WindowEventMap extends UzEventMap {
    load: UzumakiEvent;
    close: UzumakiEvent;
    resize: UzumakiResizeEvent;
  }
  type EventName = keyof UzEventMap;
  type WindowEventName = keyof WindowEventMap;
  type EventHandler<K extends EventName = EventName> = (
    event: UzEventMap[K],
  ) => void;
  type WindowEventHandler<K extends WindowEventName = WindowEventName> = (
    event: WindowEventMap[K],
  ) => void;
  interface InternalFlags {
    _stopped: boolean;
    _stoppedImmediate: boolean;
    _prevented: boolean;
    _phase: EventPhase;
  }
  interface UzEventInit<T extends UzNode = UzNode> {
    bubbles?: boolean;
    currentTarget?: T | null;
    eventPhase?: EventPhase;
  }
  declare class UzEvent<T extends UzNode = UzNode> implements UzumakiEvent<T> {
    readonly type: EventType | string;
    currentTarget: T | null;
    readonly bubbles: boolean;
    private _target;
    private readonly _flags;
    constructor(
      type: EventType | string,
      targetOrInit?: UzNode | UzEventInit<T> | null,
      init?: UzEventInit<T>,
    );
    get target(): UzNode | null;
    get eventPhase(): EventPhase;
    get defaultPrevented(): boolean;
    stopPropagation(): void;
    stopImmediatePropagation(): void;
    preventDefault(): void;
    /** @internal */
    _getFlags(): InternalFlags;
    /** @internal */
    _setPhase(phase: EventPhase): void;
    /** @internal */
    _setTarget(target: UzNode | null): void;
  }
  //#endregion
  //#region js/elements/element.d.ts
  declare class Element<M extends UzEventMap = UzEventMap> extends UzNode {
    private _elementId;
    /** @internal */
    readonly _emitter: UzEventTarget<M>;
    constructor(window: Window, native: CoreNode);
    get id(): string | null;
    set id(value: string | null);
    on<K extends keyof M>(
      name: K,
      handler: (event: M[K]) => void,
      options?: ListenerOptions,
    ): void;
    off<K extends keyof M>(
      name: K,
      handler: (event: M[K]) => void,
      options?: ListenerOptions,
    ): void;
    emit<K extends keyof M>(name: K, event: M[K]): boolean;
    focus(): void;
    setAttribute(name: string, value: unknown): void;
    setAttributes(attributes: Record<string, unknown>): void;
    removeAttribute(name: string): void;
    getAttribute(name: string): unknown;
    destroy(): void;
  }
  //#endregion
  //#region js/elements/root.d.ts
  declare class UzRootElement extends Element {
    readonly type = '#root';
    constructor(window: Window);
  }
  //#endregion
  //#region js/elements/base.d.ts
  declare class UzElement<
    M extends UzEventMap = UzEventMap,
  > extends Element<M> {
    readonly type: string;
    constructor(type: string, window: Window);
  }
  //#endregion
  //#region js/elements/view.d.ts
  declare class UzViewElement extends UzElement {
    constructor(window: Window);
  }
  //#endregion
  //#region js/elements/text.d.ts
  declare class UzTextElement extends UzElement {
    constructor(window: Window);
  }
  //#endregion
  //#region js/elements/button.d.ts
  declare class UzButtonElement extends UzElement {
    constructor(window: Window);
  }
  //#endregion
  //#region js/elements/image.d.ts
  interface ImageLoadEvent {
    readonly src: string;
  }
  interface ImageErrorEvent {
    readonly src: string;
    readonly message: string;
  }
  interface ImageEventMap extends UzEventMap {
    load: ImageLoadEvent;
    loadstart: ImageLoadEvent;
    error: ImageErrorEvent;
  }
  declare class UzImageElement extends UzElement<ImageEventMap> {
    private _generation;
    private _disposed;
    private _src;
    constructor(window: Window);
    get src(): string | undefined;
    set src(value: string | undefined | null);
    private _load;
    private _loadAsync;
    private _safeEmit;
    private _isCurrent;
    destroy(): void;
  }
  //#endregion
  //#region js/elements/input.d.ts
  interface InputEventMap extends UzEventMap {
    /**
     * Fires before a pending text change is applied. Call `preventDefault()` to
     * cancel the change (e.g. for input filtering). Native may not emit this for
     * every modification source yet.
     */
    beforeinput: UzInputEvent;
    valuechange: string;
  }
  declare class UzInputElement extends UzElement<InputEventMap> {
    constructor(window: Window);
    get value(): string;
  }
  //#endregion
  //#region js/elements/checkbox.d.ts
  interface CheckboxEventHandlerMap extends UzEventMap {
    valuechange: boolean;
  }
  declare class UzCheckboxElement extends UzElement<CheckboxEventHandlerMap> {
    constructor(window: Window);
    get checked(): boolean;
  }
  //#endregion
  //#region js/window.d.ts
  declare const ELEMENT_CONSTRUCTORS: {
    view: typeof UzViewElement;
    text: typeof UzTextElement;
    button: typeof UzButtonElement;
    input: typeof UzInputElement;
    checkbox: typeof UzCheckboxElement;
    image: typeof UzImageElement;
  };
  type ElementTagName = keyof typeof ELEMENT_CONSTRUCTORS;
  type ElementForTag<T extends ElementTagName> = InstanceType<
    (typeof ELEMENT_CONSTRUCTORS)[T]
  >;
  declare class Window {
    private _id;
    private _native;
    private _label;
    private _remBase;
    private _disposed;
    private _disposables;
    private _root;
    /** @internal Used by the dispatcher and runtime glue. */
    readonly _emitter: UzEventTarget<WindowEventMap>;
    constructor(label: string, attributes?: WindowOptions);
    close(): void;
    addDisposable(cb: () => void): void;
    static _getById(id: number): Window | undefined;
    set title(title: string);
    set decorations(decorations: boolean);
    set visible(visible: boolean);
    set transparent(transparent: boolean);
    set resizable(resizable: boolean);
    set maximized(maximized: boolean);
    set minimized(minimized: boolean);
    set fullscreen(fullscreen: boolean);
    set windowLevel(windowLevel: WindowLevel);
    setMinSize(width: number, height: number): void;
    setMaxSize(width: number, height: number): void;
    setPosition(x: number, y: number): void;
    set theme(theme: WindowTheme);
    focus(): void;
    set contentProtected(contentProtected: boolean);
    set closable(closable: boolean);
    set minimizable(minimizable: boolean);
    set maximizable(value: boolean);
    get scaleFactor(): number;
    get innerWidth(): number;
    get innerHeight(): number;
    get title(): string;
    get visible(): boolean;
    get transparent(): boolean;
    get resizable(): boolean;
    get decorations(): boolean;
    get maximized(): boolean;
    get minimized(): boolean;
    get fullscreen(): boolean;
    get alwaysOnTop(): boolean;
    get alwaysOnBottom(): boolean;
    get windowLevel(): WindowLevel;
    get innerSize(): WindowSize | null;
    get outerSize(): WindowSize | null;
    get position(): WindowPosition | null;
    get theme(): WindowTheme | null;
    get active(): boolean | null;
    get contentProtected(): boolean;
    get closable(): boolean;
    get minimizable(): boolean;
    get maximizable(): boolean;
    get label(): string;
    get id(): number;
    get root(): UzRootElement;
    createElement<T extends ElementTagName>(type: T): ElementForTag<T>;
    createElement(type: string): Element<any>;
    createTextNode(text: string): UzTextNode;
    get isDisposed(): boolean;
    get remBase(): number;
    set remBase(value: number);
    on<K extends WindowEventName>(
      eventName: K,
      handler: WindowEventHandler<K>,
      options?: ListenerOptions,
    ): void;
    off<K extends WindowEventName>(
      eventName: K,
      handler: WindowEventHandler<K>,
      options?: ListenerOptions,
    ): void;
    /** @internal Fire a lifecycle event (load/close/resize). */
    _dispatchLifecycle(
      name: 'load' | 'close' | 'resize',
      payload?: any,
    ): boolean;
  }
  declare function getWindow(label: string): Window | undefined;
  //#endregion
  //#region js/node.d.ts
  declare class UzNode {
    readonly _native: CoreNode;
    readonly _window: Window;
    constructor(window: Window, native: CoreNode);
    static fromNodeId(window: Window, nodeId: NodeId | null): UzNode | null;
    get nodeId(): NodeId;
    get windowId(): number;
    get nodeType(): number;
    get parentNode(): UzNode | null;
    get firstChild(): UzNode | null;
    get lastChild(): UzNode | null;
    get nextSibling(): UzNode | null;
    get previousSibling(): UzNode | null;
    get textContent(): string | null;
    set textContent(text: string | null);
    appendChild<T extends UzNode>(child: T): T;
    insertBefore<T extends UzNode>(child: T, before: UzNode | null): T;
    removeChild<T extends UzNode>(child: T): T;
    /**
     * Detach this node from its parent
     */
    remove(): void;
    destroy(): void;
  }
  declare class UzTextNode extends UzNode {
    constructor(window: Window, text: string);
  }
  //#endregion
  //#region js/registry.d.ts
  declare function __internalDebugNodeCount(windowID: number): number;
  //#endregion
  //#region js/clipboard.d.ts
  declare const Clipboard: {
    readText(): string | null;
    writeText(text: string): boolean;
  };
  //#endregion
  export {
    Clipboard,
    Element,
    UzEventTarget as EventEmitter,
    type EventHandler,
    type EventName,
    EventPhase,
    EventType,
    UzButtonElement,
    UzCheckboxElement,
    type UzClipboardEvent,
    UzElement,
    UzEvent,
    type UzEventMap,
    type UzFocusEvent,
    UzImageElement,
    UzInputElement,
    type UzInputEvent,
    type UzKeyboardEvent,
    type UzMouseEvent,
    UzNode,
    UzRootElement,
    UzTextElement,
    UzTextNode,
    UzViewElement,
    type UzumakiEvent,
    type UzumakiResizeEvent,
    Window,
    type WindowEventHandler,
    type WindowEventMap,
    type WindowEventName,
    type WindowLevel,
    type WindowOptions,
    type WindowPosition,
    type WindowSize,
    type WindowTheme,
    __internalDebugNodeCount,
    getWindow,
  };
}
