import { build } from 'tsdown';
import { $ } from 'bun';
import path from 'node:path';

await build({
  entry: ['js/runtime.ts'],
  dts: { emitDtsOnly: true },
  outDir: 'dist',
  cwd: path.resolve('crates/uzumaki'),
});

const builtFile = path.resolve('crates/uzumaki/dist/runtime.d.mts');
const distDir = path.dirname(builtFile);

const file = Bun.file(builtFile);
const content = await file.text();
const final = `
/*
 * This file is generated by scripts/generate-types.js
 * Do not edit this file directly.
 */

declare module 'uzumaki' {
  ${content}
}
`.trim();

const outFile = path.resolve('packages/uzumaki-types/uzumaki.d.ts');

await Bun.write(outFile, final);

await $`rm -rf ${distDir}`;
