use std::str::FromStr;

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub(crate) enum PropKey {
    W,
    H,
    P,
    Px,
    Py,
    Pt,
    Pb,
    Pl,
    Pr,
    M,
    Mx,
    My,
    Mt,
    Mb,
    Ml,
    Mr,
    Flex,
    FlexDir,
    FlexGrow,
    FlexShrink,
    Items,
    Justify,
    Gap,
    Bg,
    Color,
    FontSize,
    FontWeight,
    Rounded,
    RoundedTL,
    RoundedTR,
    RoundedBR,
    RoundedBL,
    Border,
    BorderTop,
    BorderRight,
    BorderBottom,
    BorderLeft,
    BorderColor,
    Opacity,
    Display,
    Cursor,
    Interactive,
    Visibility,
    HoverBg,
    HoverColor,
    HoverOpacity,
    HoverBorderColor,
    ActiveBg,
    ActiveColor,
    ActiveOpacity,
    ActiveBorderColor,
    Scrollable,
    MinW,
    MinH,
    TextSelect,
    OverflowWrap,
    WordBreak,
    Position,
    Top,
    Right,
    Bottom,
    Left,
}

impl FromStr for PropKey {
    type Err = ();

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        Ok(match value {
            "w" => Self::W,
            "h" => Self::H,
            "minW" => Self::MinW,
            "minH" => Self::MinH,
            "p" => Self::P,
            "px" => Self::Px,
            "py" => Self::Py,
            "pt" => Self::Pt,
            "pb" => Self::Pb,
            "pl" => Self::Pl,
            "pr" => Self::Pr,
            "m" => Self::M,
            "mx" => Self::Mx,
            "my" => Self::My,
            "mt" => Self::Mt,
            "mb" => Self::Mb,
            "ml" => Self::Ml,
            "mr" => Self::Mr,
            "flex" => Self::Flex,
            "flexDir" => Self::FlexDir,
            "flexGrow" => Self::FlexGrow,
            "flexShrink" => Self::FlexShrink,
            "items" => Self::Items,
            "justify" => Self::Justify,
            "gap" => Self::Gap,
            "bg" => Self::Bg,
            "color" => Self::Color,
            "fontSize" => Self::FontSize,
            "fontWeight" => Self::FontWeight,
            "rounded" => Self::Rounded,
            "roundedTL" => Self::RoundedTL,
            "roundedTR" => Self::RoundedTR,
            "roundedBR" => Self::RoundedBR,
            "roundedBL" => Self::RoundedBL,
            "border" => Self::Border,
            "borderTop" => Self::BorderTop,
            "borderRight" => Self::BorderRight,
            "borderBottom" => Self::BorderBottom,
            "borderLeft" => Self::BorderLeft,
            "borderColor" => Self::BorderColor,
            "opacity" => Self::Opacity,
            "display" => Self::Display,
            "cursor" => Self::Cursor,
            "interactive" => Self::Interactive,
            "visibility" => Self::Visibility,
            "hover:bg" => Self::HoverBg,
            "hover:color" => Self::HoverColor,
            "hover:opacity" => Self::HoverOpacity,
            "hover:borderColor" => Self::HoverBorderColor,
            "active:bg" => Self::ActiveBg,
            "active:color" => Self::ActiveColor,
            "active:opacity" => Self::ActiveOpacity,
            "active:borderColor" => Self::ActiveBorderColor,
            "scrollable" => Self::Scrollable,
            "selectable" => Self::TextSelect,
            "overflowWrap" => Self::OverflowWrap,
            "wordBreak" => Self::WordBreak,
            "position" => Self::Position,
            "top" => Self::Top,
            "right" => Self::Right,
            "bottom" => Self::Bottom,
            "left" => Self::Left,
            _ => return Err(()),
        })
    }
}
